### PR TITLE
Add templates and sample for the latest power flow card

### PR DESCRIPTION
**Pull request by slipx06**
The current template file and sample is based on a very old version of the card. I've included template sensors to easily map to the latest version of the sunsynk power flow card as well as a new sample configuration.

### CODE REVIEW

**Comment by gdwaterworth** [comment]
On your "blank" lines. 2 of them have hidden tabs that break configuration.yaml 
This is in the templates file.

**Comment by slipx06** [comment]
I've removed them. Thanks

**Comment by gdwaterworth** [comment]
Busy looking at it. Card is not displaying right values. Will try get more info

**Comment by slipx06** [comment]
Not sure if it makes any difference but I used region 2 flows

**Comment by gdwaterworth** [comment]
It shouldn't. Region 2 is a copy of region 1. Only difference is the url and extra options needed on the orrigional login. Is region 2 working fine for you ?

I will look further into it tomorrow, but the problem is on grud values.

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by slipx06** [comment]
Region 2 seems to be working fine

**Comment by slipx06** [comment]
I don't think the Aux attribute is correct, It seems to be PV input. I read it from [sensor.sunsynk_output] poweraux

**Pull request merged**
